name: Deploy Worker to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'apps/worker/**'
      - '.github/workflows/deploy-worker.yml'
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: scanneo-worker
  REGION: europe-west2 # London

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check environment
        run: |
          echo "PROJECT_ID is: '${{ secrets.GCP_PROJECT_ID }}'"
          if [ -z "${{ secrets.GCP_PROJECT_ID }}" ]; then
            echo "ERROR: GCP_PROJECT_ID secret is not set!"
            echo "Please add it in GitHub Settings > Secrets > Actions"
            exit 1
          fi

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker

      - name: Build Docker image
        run: |
          docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
            -t gcr.io/$PROJECT_ID/$SERVICE_NAME:latest \
            apps/worker/

      - name: Push Docker image
        run: |
          docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA
          docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
            --platform managed \
            --region $REGION \
            --set-env-vars DATABASE_URL=${{ secrets.DATABASE_URL }} \
            --set-env-vars ORS_API_KEY=${{ secrets.ORS_API_KEY }} \
            --set-env-vars ENVIRONMENT=production \
            --set-env-vars LOG_LEVEL=INFO \
            --set-env-vars POLL_INTERVAL=30 \
            --set-env-vars JOB_TIMEOUT=3600 \
            --min-instances 0 \
            --max-instances 3 \
            --memory 1Gi \
            --cpu 1 \
            --timeout 900 \
            --allow-unauthenticated
