name: Deploy Worker to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'apps/worker/**'
      - '.github/workflows/deploy-worker.yml'
  workflow_dispatch:

env:
  SERVICE_NAME: scanneo-worker
  REGION: europe-west2 # London

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify configuration
        run: |
          echo "Service: $SERVICE_NAME"
          echo "Region: $REGION"
          echo "GitHub SHA: $GITHUB_SHA"
          echo "Checking if secrets are configured..."

          # Check if secrets exist (they'll be masked in output)
          if [ -z '${{ secrets.GCP_SA_KEY }}' ]; then
            echo "ERROR: GCP_SA_KEY secret is not set!"
            echo "Please add your service account JSON key in GitHub Settings > Secrets > Actions"
            exit 1
          fi

          if [ -z '${{ secrets.GCP_PROJECT_ID }}' ]; then
            echo "ERROR: GCP_PROJECT_ID secret is not set!"
            echo "Please add your Google Cloud project ID in GitHub Settings > Secrets > Actions"
            exit 1
          fi

          echo "All required secrets appear to be configured"

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          create_credentials_file: true
          export_environment_variables: true

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure GCP and Docker
        run: |
          echo "Setting up Google Cloud configuration..."
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

          echo "Current project:"
          gcloud config get-value project

          echo "Configuring Docker authentication..."
          # Try both GCR and Artifact Registry
          gcloud auth configure-docker gcr.io --quiet || true
          gcloud auth configure-docker $REGION-docker.pkg.dev --quiet || true

          echo "Testing authentication..."
          gcloud auth list

          echo "Checking available services:"
          gcloud services list --enabled 2>/dev/null | grep -E "(run|container|artifact)" || echo "Cannot list services (permission needed)"

      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          # Use Artifact Registry if available, fallback to GCR
          IMAGE_REPO="${REGION}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/scanneo-docker"
          GCR_REPO="gcr.io/${{ secrets.GCP_PROJECT_ID }}"

          # Check if Artifact Registry is available
          if gcloud artifacts repositories describe scanneo-docker --location=$REGION 2>/dev/null; then
            echo "Using Artifact Registry: $IMAGE_REPO"
            IMAGE_BASE="$IMAGE_REPO/$SERVICE_NAME"
          else
            echo "Using Container Registry: $GCR_REPO"
            IMAGE_BASE="$GCR_REPO/$SERVICE_NAME"
          fi

          docker build -t $IMAGE_BASE:$GITHUB_SHA \
            -t $IMAGE_BASE:latest \
            apps/worker/

          echo "IMAGE_BASE=$IMAGE_BASE" >> $GITHUB_ENV
          echo "Docker build completed"

      - name: Debug Docker and permissions
        run: |
          echo "Docker images built:"
          docker images | grep scanneo || true

          echo "Checking IAM permissions (if available):"
          gcloud projects get-iam-policy ${{ secrets.GCP_PROJECT_ID }} \
            --flatten="bindings[].members" \
            --filter="bindings.members:github-actions@" \
            --format="table(bindings.role)" 2>/dev/null || echo "Cannot check IAM (permission needed)"

      - name: Push Docker image
        run: |
          echo "Pushing Docker image..."
          IMAGE_BASE="${{ env.IMAGE_BASE }}"
          docker push $IMAGE_BASE:$GITHUB_SHA
          docker push $IMAGE_BASE:latest
          echo "Push completed"

      - name: Deploy to Cloud Run
        run: |
          IMAGE_BASE="${{ env.IMAGE_BASE }}"
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE_BASE:$GITHUB_SHA \
            --platform managed \
            --region $REGION \
            --set-env-vars "DATABASE_URL=${{ secrets.DATABASE_URL }},ORS_API_KEY=${{ secrets.ORS_API_KEY }},ENVIRONMENT=production,LOG_LEVEL=INFO,POLL_INTERVAL=30,JOB_TIMEOUT=3600" \
            --min-instances 0 \
            --max-instances 3 \
            --memory 1Gi \
            --cpu 1 \
            --timeout 900 \
            --allow-unauthenticated
